# -*- coding: utf-8 -*-
"""bandwidth_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCzNuYc2lISOlQ23fF2-zBoG4Ahiw_Iv
"""

def calculate_bandwidth(gossip_interval, gossip_fanout, nodes,
                       packet_size=1024, overhead=1.2):
    """
    Рассчитать пропускную способность для Gossip протокола

    Формула:
    messages_per_second = nodes * fanout / interval
    bandwidth_bps = messages_per_second * packet_size * overhead * 8

    Возвращает: bandwidth в Кбит/с
    """
    messages_per_second = nodes * gossip_fanout / gossip_interval
    bandwidth_bps = messages_per_second * packet_size * overhead * 8
    return bandwidth_bps / 1000  # Кбит/с


def compare_protocols(nodes=50, packet_size=1024, interval=0.2):
    """
    Сравнить Gossip и Heartbeat

    Рассчитать для обоих протоколов:
    - Пропускную способность на узел
    - Общую пропускную способность

    Вывести сравнительную таблицу
    """
    # Gossip
    gossip_fanout = 3
    gossip_per_node = (gossip_fanout * packet_size * 8) / interval / 1000
    gossip_total = gossip_per_node * nodes

    # Heartbeat
    heartbeat_per_node = (packet_size * 8) / interval / 1000
    heartbeat_total = heartbeat_per_node * nodes

    return {
        'gossip': {
            'per_node_kbps': gossip_per_node,
            'total_kbps': gossip_total
        },
        'heartbeat': {
            'per_node_kbps': heartbeat_per_node,
            'total_kbps': heartbeat_total
        }
    }


if __name__ == '__main__':
    # Эксперимент: варьировать Gossip Interval
    intervals = [0.1, 0.2, 0.5, 1.0]

    print("Gossip Interval | Пропускная способность")
    print("-" * 45)
    for interval in intervals:
        bandwidth = calculate_bandwidth(interval, 3, 50)
        print(f"{interval:^15} | {bandwidth:,.2f} Кбит/с")

    print("\n" + "="*45 + "\n")
    comparison = compare_protocols(nodes=50)
    print("Сравнение протоколов для 50 узлов:")
    print(f"Gossip - на узел: {comparison['gossip']['per_node_kbps']:.2f} Кбит/с, всего: {comparison['gossip']['total_kbps']:.2f} Кбит/с")
    print(f"Heartbeat - на узел: {comparison['heartbeat']['per_node_kbps']:.2f} Кбит/с, всего: {comparison['heartbeat']['total_kbps']:.2f} Кбит/с")